# Generated by Django 2.2.10 on 2021-02-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201209_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
